from __future__ import annotations

import psycopg
from psycopg.rows import dict_row

from app.config import settings


SCHEMA = """
CREATE TABLE IF NOT EXISTS watch_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debox_user_id TEXT NOT NULL,
    chain_key TEXT NOT NULL DEFAULT 'bsc',
    chain_id INTEGER NOT NULL,
    wallet_address TEXT NOT NULL,
    token_address TEXT,
    rule_type TEXT NOT NULL,
    threshold TEXT NOT NULL,
    notification_chat_id TEXT NOT NULL,
    notification_chat_type TEXT NOT NULL,
    notification_label TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    last_value TEXT,
    last_checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debox_user_id TEXT NOT NULL,
    plan_code TEXT NOT NULL,
    status TEXT NOT NULL,
    starts_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    scheduled_push_last_sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debox_user_id TEXT NOT NULL,
    payer_address TEXT,
    chain_key TEXT NOT NULL DEFAULT 'bsc',
    chain_id INTEGER NOT NULL,
    token_address TEXT,
    recipient_address TEXT,
    payment_contract_address TEXT,
    total_amount TEXT NOT NULL,
    plan_code TEXT NOT NULL DEFAULT 'standard',
    tx_hash TEXT,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_rule_id INTEGER NOT NULL REFERENCES watch_rules(id),
    event_type TEXT NOT NULL,
    previous_value TEXT,
    current_value TEXT,
    notification_message_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debox_user_id TEXT NOT NULL,
    gid TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (debox_user_id, gid)
);
"""

MIGRATIONS = [
    "ALTER TABLE watch_rules ADD COLUMN IF NOT EXISTS chain_key TEXT NOT NULL DEFAULT 'bsc'",
    "ALTER TABLE watch_rules ADD COLUMN IF NOT EXISTS notification_label TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS chain_key TEXT NOT NULL DEFAULT 'bsc'",
    "ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS scheduled_push_last_sent_at TIMESTAMPTZ",
]


def connect() -> psycopg.Connection:
    if not settings.database_url:
        raise RuntimeError("DATABASE_URL is required. Configure PostgreSQL before starting the app.")
    return psycopg.connect(settings.database_url, row_factory=dict_row)


def fetch_inserted(connection: psycopg.Connection, cursor, table: str) -> dict:
    row_id = cursor.fetchone()["id"]
    row = connection.execute(f"SELECT * FROM {table} WHERE id = %s", (row_id,)).fetchone()
    return dict(row)


def initialize_database() -> None:
    with connect() as connection:
        for statement in SCHEMA.split(";"):
            statement = statement.strip()
            if statement:
                connection.execute(statement)
        for statement in MIGRATIONS:
            connection.execute(statement)


def expire_pending_orders(minutes: int = 30, expire_all: bool = False) -> int:
    with connect() as connection:
        if expire_all:
            cursor = connection.execute("UPDATE orders SET status = 'expired' WHERE status = 'pending'")
        else:
            cursor = connection.execute(
                """
                UPDATE orders
                SET status = 'expired'
                WHERE status = 'pending'
                  AND created_at <= CURRENT_TIMESTAMP - (%s * INTERVAL '1 minute')
                """,
                (minutes,),
            )
        return cursor.rowcount


def create_watch_rule(
    debox_user_id: str,
    chain_key: str,
    chain_id: int,
    wallet_address: str,
    token_address: str | None,
    rule_type: str,
    threshold: str,
    notification_chat_id: str,
    notification_chat_type: str,
    notification_label: str = "",
) -> dict:
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO watch_rules (
                debox_user_id, chain_key, chain_id, wallet_address, token_address,
                rule_type, threshold, notification_chat_id, notification_chat_type,
                notification_label
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                debox_user_id,
                chain_key,
                chain_id,
                wallet_address,
                token_address,
                rule_type,
                threshold,
                notification_chat_id,
                notification_chat_type,
                notification_label,
            ),
        )
        return fetch_inserted(connection, cursor, "watch_rules")


def count_user_watch_rules(debox_user_id: str) -> int:
    with connect() as connection:
        row = connection.execute(
            "SELECT COUNT(*) AS count FROM watch_rules WHERE debox_user_id = %s AND enabled = 1",
            (debox_user_id,),
        ).fetchone()
    return int(row["count"])


def list_user_watch_rules(debox_user_id: str) -> list[dict]:
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT * FROM watch_rules
            WHERE debox_user_id = %s
            ORDER BY id DESC
            """,
            (debox_user_id,),
        ).fetchall()
    return [dict(row) for row in rows]


def list_enabled_watch_rules() -> list[dict]:
    with connect() as connection:
        rows = connection.execute("SELECT * FROM watch_rules WHERE enabled = 1 ORDER BY id").fetchall()
    return [dict(row) for row in rows]


def update_watch_rule_value(rule_id: int, value: str) -> None:
    with connect() as connection:
        connection.execute(
            """
            UPDATE watch_rules
            SET last_value = %s, last_checked_at = CURRENT_TIMESTAMP
            WHERE id = %s
            """,
            (value, rule_id),
        )


def delete_watch_rule(debox_user_id: str, rule_id: int) -> None:
    with connect() as connection:
        connection.execute(
            """
            UPDATE watch_rules
            SET enabled = 0
            WHERE debox_user_id = %s AND id = %s
            """,
            (debox_user_id, rule_id),
        )


def create_alert_event(
    watch_rule_id: int,
    event_type: str,
    previous_value: str,
    current_value: str,
    notification_message_id: str = "",
) -> None:
    with connect() as connection:
        connection.execute(
            """
            INSERT INTO alert_events (
                watch_rule_id, event_type, previous_value,
                current_value, notification_message_id
            ) VALUES (%s, %s, %s, %s, %s)
            """,
            (watch_rule_id, event_type, previous_value, current_value, notification_message_id),
        )


def create_order(
    debox_user_id: str,
    payer_address: str,
    token_address: str | None,
    recipient_address: str,
    payment_contract_address: str,
    total_amount: str,
    plan_code: str,
) -> dict:
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO orders (
                debox_user_id, payer_address, chain_key, chain_id, token_address,
                recipient_address, payment_contract_address,
                total_amount, plan_code, status
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, 'pending')
            RETURNING id
            """,
            (
                debox_user_id,
                payer_address,
                settings.chain_key,
                settings.chain_id,
                token_address,
                recipient_address,
                payment_contract_address,
                total_amount,
                plan_code,
            ),
        )
        return fetch_inserted(connection, cursor, "orders")


def get_order(order_id: int) -> dict | None:
    with connect() as connection:
        row = connection.execute("SELECT * FROM orders WHERE id = %s", (order_id,)).fetchone()
    return dict(row) if row else None


def complete_order(order_id: int, tx_hash: str) -> dict:
    with connect() as connection:
        connection.execute(
            """
            UPDATE orders
            SET tx_hash = %s, status = 'paid'
            WHERE id = %s AND status = 'pending'
            """,
            (tx_hash, order_id),
        )
        row = connection.execute("SELECT * FROM orders WHERE id = %s", (order_id,)).fetchone()
    return dict(row)


def expire_active_subscriptions(connection: psycopg.Connection, debox_user_id: str | None = None) -> None:
    if debox_user_id:
        connection.execute(
            """
            UPDATE subscriptions
            SET status = 'expired'
            WHERE debox_user_id = %s AND status = 'active'
              AND expires_at <= CURRENT_TIMESTAMP
            """,
            (debox_user_id,),
        )
    else:
        connection.execute(
            """
            UPDATE subscriptions
            SET status = 'expired'
            WHERE status = 'active' AND expires_at <= CURRENT_TIMESTAMP
            """
        )


def activate_subscription(debox_user_id: str, plan_code: str, days: int) -> dict:
    with connect() as connection:
        expire_active_subscriptions(connection, debox_user_id)
        active = connection.execute(
            """
            SELECT * FROM subscriptions
            WHERE debox_user_id = %s AND status = 'active'
              AND expires_at > CURRENT_TIMESTAMP
            ORDER BY id DESC
            LIMIT 1
            """,
            (debox_user_id,),
        ).fetchone()

        if active and active["plan_code"] == plan_code:
            row = connection.execute(
                """
                UPDATE subscriptions
                SET expires_at = expires_at + (%s * INTERVAL '1 day')
                WHERE id = %s
                RETURNING *
                """,
                (days, active["id"]),
            ).fetchone()
            return dict(row)

        if active and active["plan_code"] == "free" and plan_code != "free":
            connection.execute("UPDATE subscriptions SET status = 'upgraded' WHERE id = %s", (active["id"],))
        elif active and active["plan_code"] != plan_code:
            raise ValueError("当前订阅未到期，暂时不能切换套餐；同套餐可以提前续费。")

        cursor = connection.execute(
            """
            INSERT INTO subscriptions (
                debox_user_id, plan_code, status, starts_at, expires_at
            ) VALUES (
                %s, %s, 'active', CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP + (%s * INTERVAL '1 day')
            )
            RETURNING id
            """,
            (debox_user_id, plan_code, days),
        )
        return fetch_inserted(connection, cursor, "subscriptions")


def get_active_subscription(debox_user_id: str) -> dict | None:
    with connect() as connection:
        expire_active_subscriptions(connection, debox_user_id)
        row = connection.execute(
            """
            SELECT * FROM subscriptions
            WHERE debox_user_id = %s AND status = 'active'
              AND expires_at > CURRENT_TIMESTAMP
            ORDER BY id DESC
            LIMIT 1
            """,
            (debox_user_id,),
        ).fetchone()
    return dict(row) if row else None


def has_used_plan(debox_user_id: str, plan_code: str) -> bool:
    with connect() as connection:
        row = connection.execute(
            """
            SELECT 1 FROM subscriptions
            WHERE debox_user_id = %s AND plan_code = %s
            LIMIT 1
            """,
            (debox_user_id, plan_code),
        ).fetchone()
    return row is not None


def create_notification_group(debox_user_id: str, gid: str, name: str = "") -> dict:
    with connect() as connection:
        row = connection.execute(
            """
            INSERT INTO notification_groups (debox_user_id, gid, name, enabled)
            VALUES (%s, %s, %s, 1)
            ON CONFLICT (debox_user_id, gid)
            DO UPDATE SET name = EXCLUDED.name, enabled = 1
            RETURNING *
            """,
            (debox_user_id, gid, name),
        ).fetchone()
    return dict(row)


def count_notification_groups(debox_user_id: str) -> int:
    with connect() as connection:
        row = connection.execute(
            """
            SELECT COUNT(*) AS count FROM notification_groups
            WHERE debox_user_id = %s AND enabled = 1
            """,
            (debox_user_id,),
        ).fetchone()
    return int(row["count"])


def list_notification_groups(debox_user_id: str) -> list[dict]:
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT * FROM notification_groups
            WHERE debox_user_id = %s AND enabled = 1
            ORDER BY id DESC
            """,
            (debox_user_id,),
        ).fetchall()
    return [dict(row) for row in rows]


def get_notification_group(debox_user_id: str, gid: str) -> dict | None:
    with connect() as connection:
        row = connection.execute(
            """
            SELECT * FROM notification_groups
            WHERE debox_user_id = %s AND gid = %s AND enabled = 1
            LIMIT 1
            """,
            (debox_user_id, gid),
        ).fetchone()
    return dict(row) if row else None


def delete_notification_group(debox_user_id: str, group_id: int) -> None:
    with connect() as connection:
        connection.execute(
            """
            UPDATE notification_groups
            SET enabled = 0
            WHERE debox_user_id = %s AND id = %s
            """,
            (debox_user_id, group_id),
        )


def list_due_scheduled_subscriptions(hours: int = 24) -> list[dict]:
    with connect() as connection:
        expire_active_subscriptions(connection)
        rows = connection.execute(
            """
            SELECT * FROM subscriptions
            WHERE status = 'active'
              AND plan_code IN ('standard', 'professional')
              AND expires_at > CURRENT_TIMESTAMP
              AND (
                scheduled_push_last_sent_at IS NULL
                OR scheduled_push_last_sent_at <= CURRENT_TIMESTAMP - (%s * INTERVAL '1 hour')
              )
            ORDER BY scheduled_push_last_sent_at NULLS FIRST, id
            """,
            (hours,),
        ).fetchall()
    return [dict(row) for row in rows]


def mark_scheduled_push_sent(subscription_id: int) -> None:
    with connect() as connection:
        connection.execute(
            """
            UPDATE subscriptions
            SET scheduled_push_last_sent_at = CURRENT_TIMESTAMP
            WHERE id = %s
            """,
            (subscription_id,),
        )
